version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: logi_php
    image: laravel_php
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
      - /var/www/node_modules
      - /var/www/vendor
      - ./.env.example:/var/www/.env
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: logi_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "444:443"
    volumes:
      - ./:/var/www
      - ./nginx/nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./.env.example:/var/www/.env
    environment:
      - HOSTNAME=hbr.test
    networks:
      - app-network
    volumes_from:
      - php
    depends_on:
      - php

networks:
  app-network:
    driver: bridge
